sudo: required

services:
  - docker

before_install:
  - mkdir -p ../myecp
  - curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose up -d
  - docker-compose ps |grep "apache.*443"
  - docker-compose ps |grep "mysql.*3306"
  - docker-compose ps |grep "postgres.*5432"

