code:
  image: debian:jessie
  volumes:
   - ./code/:/var/www/html
  tty: true

#phpmyadmin:
#   image: corbinu/docker-phpmyadmin
#   ports :
#    - "8081:80"
#   environment:
#    - MYSQL_USERNAME=root
#    - MYSQL_PASSWORD=password
#   links:
#    - mysql

apache:
   build: apache
   volumes_from:
     - code
   links:
     - mysql
     - postgres
#   volumes:
#     - ./logs/apache2/:/var/log/apache2
   ports:
     - "5080:80"
     - "5443:443"

mysql:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=myecp
     - MYSQL_USER=myecp
     - MYSQL_PASSWORD=myecp

postgres:
  image: postgres:9
  environment:
     - POSTGRES_PASSWORD=myecp
     - POSTGRES_USER=myecp

