apache:
   build: apache
   volumes:
   - ../myecp:/var/www/myecp
   - ./logs/apache2/:/var/log/apache2
   links:
     - mysql
     - postgres
   ports:
     - "5080:80"
     - "5443:443"

mysql:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=myecp
     - MYSQL_USER=myecp
     - MYSQL_PASSWORD=myecp

postgres:
  image: postgres:9
  environment:
     - POSTGRES_PASSWORD=myecp
     - POSTGRES_USER=myecp

