site:
  build: site
  ports :
   - "8080:80"
  volumes:
   - ./code/:/var/www/html
  links:
   - mysql

phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8081:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=password
   links:
    - mysql

mysql:
  image: mysql:5.6
  environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=myecp
     - MYSQL_USER=myecp
     - MYSQL_PASSWORD=myecp
